name: google_cloudevents_dart
description: An SDK for working with CloudEvents in Dart.
version: 0.0.1+2
repository: https://github.com/a-wallen/google_cloudevents_dart.git
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
dependencies:
  analyzer: ^6.4.1
  fixnum: ^1.1.0
  logging: ^1.2.0
  protobuf: ^3.1.0
